Style_arr   Style_t <02DBh, 0220h, 0A3Eh, 0000h>   ; 0 - green
            Style_t <4c03h or 8000h, 4c00h, 0FFFFh, 0000h> ; 1 - hearts
            Style_t <8423h, 0420h, 0C21h, 0000h>   ; 2 - blinking red 
            Style_t <1FC9h, 1F20h, 1E41h, 0000h>   ; 3 - blue
            Style_t <07B0h, 0720h, 0F7Eh, 0000h>   ; 4 - grey
            Style_t <03B2h, 0320h, 0B2Bh, 0000h>   ; 5 - cyan
            Style_t <06CDh, 0620h, 0E41h, 0000h>   ; 6 - orange
            Style_t <70C9h, 7020h, 7041h, 0000h>   ; 7 - invers
            Style_t <05DBh, 0520h, 0D41h, 0000h>   ; 8 - purple
            Style_t <02C9h, 0220h, 0A41h, 0000h>   ; 9 - green
            Style_t <0EC9h, 0E20h, 0E41h, 0000h>   ; 10- yellow
            Style_t <0CC9h, 0C20h, 0C41h, 0000h>   ; 11- bright red
            Style_t <0FB0h, 0F20h, 0F40h, 0000h>   ; 12 - white
            Style_t <7041h, 7F20h, 7041h, 0000h>
            Style_t <09C9h, 1111h, 1E41h, 0000h>  ; 13 - bright blue
            Style_t <84C9h, 0420h, 0C21h, 0000h>   ; 14 - blinking red